### ISSUE TITLE
Custom message converter for Azure Functions ServiceBusTrigger

### ISSUE THREAD

**Issue by SeanFeldman** [SeanFeldman/ServiceBus.AttachmentPlugin#101]
[Original](https://github.com/SeanFeldman/ServiceBus.AttachmentPlugin/pull/97#issuecomment-477575645) comment by @jstclair:

>Great timing! I've done something similar, but rather than write extension methods off message, I'd just copied some of the underlying implementation into our (receiving) functions.
>
>Sean, now that Azure Functions supports user-extensible triggers, how would feel about taking/creating a sub-project to extend the existing ServiceBus(x)Trigger with the attachments plugin support? [Here's an example on extending the existing Cosmos trigger to support POCOs](https://www.tpeczek.com/2019/01/azure-functions-20-extensibility.html)

**Comment by SeanFeldman** [comment]
@jstclair that sounds like a good idea if someone wants to use it with Functions 2.x.
I've went through some of the [official documentation](https://github.com/Azure/azure-webjobs-sdk/wiki/Creating-custom-input-and-output-bindings#3-add-converters) to get an idea what it would look like.

> Converters can be used for both `BindToInput` and `BindToCollector`.

Already existing converters are:
- Incoming
  - [`MessageToByteArrayConverter : IAsyncConverter<Message, byte[]>`](https://github.com/Azure/azure-webjobs-sdk/blob/dev/src/Microsoft.Azure.WebJobs.Extensions.ServiceBus/Triggers/MessageToByteArrayConverter.cs)
  - [`MessageToStringConverter : IAsyncConverter<Message, string>`](https://github.com/Azure/azure-webjobs-sdk/blob/dev/src/Microsoft.Azure.WebJobs.Extensions.ServiceBus/Triggers/MessageToStringConverter.cs)
- Outgoing
  - [`StringToBinarydMessageConverter : IConverter<string, Message>`](https://github.com/Azure/azure-webjobs-sdk/blob/dev/src/Microsoft.Azure.WebJobs.Extensions.ServiceBus/Triggers/StringToBinaryMessageConverter.cs)
  - [`StringToJsonMessageConverter : IConverter<string, Message>`](https://github.com/Azure/azure-webjobs-sdk/blob/dev/src/Microsoft.Azure.WebJobs.Extensions.ServiceBus/Triggers/StringToJsonMessageConverter.cs)
  - [`StringToTextMessageConverter : IConverter<string, Message>`](https://github.com/Azure/azure-webjobs-sdk/blob/dev/src/Microsoft.Azure.WebJobs.Extensions.ServiceBus/Triggers/StringToTextMessageConverter.cs)

The [trigger](https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-service-bus#trigger---usage) supports the following parameter types
- `Message`
- `string`
- `byte[]`
- A custom type - If the message contains JSON, Azure Functions tries to deserialize the JSON data.

The [output binding](https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-service-bus#output---usage) supports the following types
- `IAsyncCollector<T> paramName`/ `out T paramName` - `T` can be any JSON-serializable type. If the parameter value is null when the function exits, Functions creates the message with a null object.
- `IAsyncCollector<string>`/`out string` - If the parameter value is null when the function exits, Functions does not create a message.
- `IAsyncCollector<byte[]>`/`out byte[]` - If the parameter value is null when the function exits, Functions does not create a message.
- `IAsyncCollector<Message>`/`out Message` - If the parameter value is null when the function exits, Functions does not create a message.
- `IAsyncCollector<T>`/`ICollector<T>` - For creating multiple messages. A message is created when you call the Add method.

I'm not entirely sure yet how it will work, but we can start a PR to get the ball rolling. Would you like to help?

**Comment by jstclair** [comment]
Sure. I'll have some time this weekend. Just to be clear, since you are mentioning the binding - the idea would be to use the Message extension methods from the previous PR in the converter implementation(s)?

**Comment by SeanFeldman** [comment]
Haven't looked into details, but I'd think so if we get message in/out. Would be interesting to see how custom configuration would be specified with Functions framework.

**Comment by SeanFeldman** [comment]
@jstclair have you had a chance to look into this?

**Comment by SeanFeldman** [comment]
@jstclair I'm going to close the issue as there seems to be no traction on it. In case you do have an update, let me know and I'll re-open it. Thank you.
