### ISSUE TITLE
The given key '$attachment.blob' was not present in the dictionary

### ISSUE THREAD

**Issue by msalzig** [SeanFeldman/ServiceBus.AttachmentPlugin#112]
Hello Sean,

I use your plugin. When I receive a message, I get the following error message: The given key '$ attachment.blob' was not present in the dictionary. Looks like the file no longer exists in the blob storage. Can you help me here? Do you have an idea why this may be?

greeting
Michael

**Comment by SeanFeldman** [comment]
Michael, I'm having a difficulty to locate this exception in the code. If the key is not found, the message is returned as-is and expected to be a message w/o an attachment ([code](https://github.com/SeanFeldman/ServiceBus.AttachmentPlugin/blob/da8c170fad6e4001026ed0441a9b7b0a6f005b0f/src/ServiceBus.AttachmentPlugin/AzureStorageAttachment.cs#L108-L111)). Hence this error is a bit of a surprise.

To help you better, could you please provide the following:

1. What version of the plugin are you using?
2. Full stack trace when the exception is taking place.
3. How are you sender and receiver are configured (code)?

Once you share those I'll be able to look into it.

**Comment by SeanFeldman** [comment]
@msalzig are you still experiencing the issue? If you do, please refer to my previous comment if you want assistance.

**Comment by msalzig** [comment]
Sean, Sorry for the late reply. I found the mistake. In the event that the messages are not placed in the BLOB storage, but only on the service bus, I still tried to access the BLOB storage.

**Comment by SeanFeldman** [comment]
Sounds like you're manually trying to access the blob that has never been created. In that case, the plug-in works as expected. Going to close the issue. Please report if I misunderstood.
