### ISSUE TITLE
Use Microsoft.Azure.Storage.Blob instead of WindowsAzure.Storage

### ISSUE THREAD

**Issue by SeanFeldman** [SeanFeldman/ServiceBus.AttachmentPlugin#116]
Microsoft.Azure.Storage.Blob is the continuation of WindowsAzure.Storage, specifically designed for Azure Storage Blobs.

**Comment by CasperWSchmidt** [comment]
Any ETA for 6.0.0? I would like to void dependencies on WindowsAzure.Storage in my project, but am considering this package for implementing the claim check pattern you described [here](https://www.serverless360.com/blog/deal-with-large-service-bus-messages-using-claim-check-pattern) :)

**Comment by SeanFeldman** [comment]
@CasperWSchmidt sorry, got a bit distracted. I'm hoping to get to this by the weekend and let a preview version out to see if there's anything major. If nothing is found, shortly after to have an RTM.

**Comment by SeanFeldman** [comment]
[6.0.0-preview01](https://www.nuget.org/packages/ServiceBus.AttachmentPlugin/6.0.0-preview01) is on NuGet. Give it a whirl and if no issues identified in a few days, I'll release the stable.

**Comment by SeanFeldman** [comment]
@CasperWSchmidt give it a try?

**Comment by CasperWSchmidt** [comment]
I will, but it looks good 😊

**Comment by SeanFeldman** [comment]
The tests are green, but I don't know how people use it and wherever there's an edge case or not.

**Comment by CasperWSchmidt** [comment]
I have just started using it in an internal NuGet package for our infrastructure (communication with Azure Service Bus, Application Insights etc.)
I had to wrap it though to enable unit testing but I guess that's a different issue :)

**Comment by SeanFeldman** [comment]
> I had to wrap it though to enable unit testing but I guess that's a different issue :)

Please raise the issue if that's affecting you.

Looking forward to your confirmation it's working well with the new dependencies.

**Comment by CasperWSchmidt** [comment]
Everything looks fine. I have worked around the missing interface by abstracting the library away behind my own implementation😊
I do have issues with the key vault extension however, and have created issues in that repository

**Comment by SeanFeldman** [comment]
> I do have issues with the key vault extension however, and have created issues in that repository

Sounds good. I'll have a look at those.
Thank you for verifying. I'll have a look at the keyvault issues. If they are unrelated to this repo, will push out an RTM this week.

**Comment by SeanFeldman** [comment]
I'm adding nullable reference types in v6 (C# 8) via PR #151

**Comment by SeanFeldman** [comment]
@CasperWSchmidt [AttachmentPlugin 6.0.0](https://www.nuget.org/packages/ServiceBus.AttachmentPlugin/6.0.0) and [ServiceBus.AttachmentPlugin.KeyVaultProvider 3.0.0](https://www.nuget.org/packages/ServiceBus.AttachmentPlugin.KeyVaultProvider/3.0.0) are out.
