### ISSUE TITLE
Feature suggestion - SAS uri

### ISSUE THREAD

**Issue by iremmats** [SeanFeldman/ServiceBus.AttachmentPlugin#13]
One weakness (depends on you look at it) of the current implementation is that everyone that consumes messages needs to have a connection string to the same storage account. If you send messages internally within your application this is no issue but if you send to others this will create dependencies.

At our company we have implemented Claim Check Pattern for some time too. Instead of setting a Guid as message property we set the actual path in a json body. We also include a SAS link to that specific blog, meaning that the message payload can be retrieved without the receiver having access to the entire blob storage account. 

So my suggestion is to include a sas uri in the message (somehow) to let receivers be able to consume the payload with just the connection string to service bus and rights to read the message.

**Comment by SeanFeldman** [comment]
That's an interesting idea. This allows to decouple receiver and the sender.
Are you setting the SAS link TTL to an infinite time? Can't assume when the message is going to be consumed.

**Comment by iremmats** [comment]
I think our default is 1 week. This has been working for perfectly fine for us. But its up to the sender to set that TTL depending on the scenario.

**Comment by SeanFeldman** [comment]
I like the idea. 1 week is a bit too short in some scenarios. Would have to
check what's the maximum possible.

**Comment by jtaubensee** [comment]
+1 for this idea. To @SeanFeldman's point, it probably would be best to leave the existing implementation as the default, and to add SAS tokens as something you would opt into.

**Comment by SeanFeldman** [comment]
Closed via https://github.com/SeanFeldman/ServiceBus.AttachmentPlugin/commit/71e0a7c8ca59490308fd3eb45f5387626e29601b
