### ISSUE TITLE
Add support for SB-Messaging adapter (empty message body rather than null)

### ISSUE THREAD

**Issue by jcools85** [SeanFeldman/ServiceBus.AttachmentPlugin#187]
I'm using ServiceBus.AttachmentPlugin in a hybrid integration solution, and my consumer (in this case BizTalk's SB-Messaging adapter) doesn't like the ServiceBus message body being null. 
I can replace the message body stream in the receive pipeline to let my flow work, but the SB-Messaging adapter still logs an error in the eventlog: 

> The Messaging Engine received an error from transport adapter “SB-Messaging” when notifying the adapter with the BatchComplete event. Reason “Object reference not set to an instance of an object.”.

Proposed solution:
Add an option to the AzureStorageAttachmentConfiguration constructor to avoid an empty message body when sending a message. For example, the blob.Name that is written to the custom property could also be written to the ServiceBus Message Body.

**Comment by SeanFeldman** [comment]
@jcools85 would an empty byte array work for your scenario?

**Comment by jcools85** [comment]
@SeanFeldman yes, just tested with an empty byte array and that seems to work.

**Comment by SeanFeldman** [comment]
@jcools85 have a look at the change [here](https://github.com/SeanFeldman/ServiceBus.AttachmentPlugin/pull/188/files#diff-36b458d16056022041075d230a8b45fc). This would need to be an opt-in configuration. Would that work for your scenario?

**Comment by SeanFeldman** [comment]
Also, would it be correct to say that this issue adds support for "BizTalk's Service Bus Messaging adapter"?

**Comment by jcools85** [comment]
Looks good! That would indeed work for my scenario.
And yes, you could say this adds support for the SB-Messaging adapter, because besides this little issue it works perfectly. You do however have to build the "receive" logic in BizTalk. But a simple pipeline component that replaces the body stream with a new stream from blobstorage does the trick.

**Comment by SeanFeldman** [comment]
> Looks good! That would indeed work for my scenario.

Great. I'll release that over the weekend.

> And yes, you could say this adds support for the SB-Messaging adapter, because besides this little issue it works perfectly.

Great. I love to see CodeIt leveraging this plugin for various solutions.

> You do however have to build the "receive" logic in BizTalk. But a simple pipeline component that replaces the body stream with a new stream from blobstorage does the trick.

That's likely due to the fact that the receiving part of the [SB-Messaging adapter](https://docs.microsoft.com/en-us/biztalk/core/sb-messaging-adapter) assumes the body is always there. Which is OK as long as the BT pipeline allows you to have the step before to consolidate the payload and the message.

**Comment by jcools85** [comment]
> Great. I love to see CodeIt leveraging this plugin for various solutions.

Thanks for handling this request so swiftly @SeanFeldman !
Will be used in production at one of our customers before summer :)

**Comment by SeanFeldman** [comment]
@jcools85 do you mind to share your Twitter account (for credits)?

**Comment by jcools85** [comment]
> @jcools85 do you mind to share your Twitter account (for credits)?

Sure! my twitter handle is @jcools85 as well. I just followed you, was surprised to see I wasn't following you there already, because you do pop up on my feed a lot :D

**Comment by SeanFeldman** [comment]
Found an [issue](https://github.com/SeanFeldman/ServiceBus.AttachmentPlugin/commit/5dd469013df411c6e667a86ff400930cf8bc003f) with the body replacer. Will release once the other PR for the milestone is closed.
