### ISSUE TITLE
Support for Microsoft.Azure.ServiceBus -Version 2.0.0

### ISSUE THREAD

**Issue by darrenshrwd** [SeanFeldman/ServiceBus.AttachmentPlugin#20]
Hi, 2.0.0 came out (just 19 days ago). Will this package be updated to also work with it?

I tried and it compiles, but when I run I get:
System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Azure.ServiceBus, Version=1.0.0.0

**Comment by SeanFeldman** [comment]
@darrenshrwd absolutely.

**Comment by SeanFeldman** [comment]
Closed via https://github.com/SeanFeldman/ServiceBus.AttachmentPlugin/commit/00264beaea99a073003a3a70da2d8bb531a2a7f4

**Comment by SeanFeldman** [comment]
2.0.0 released.

**Comment by darrenshrwd** [comment]
Thanks for quick response but why does it require .NET 4.6.2 ?  It is .NET 4.6.1 that is the lowest common support of .NET standard 2.0 https://docs.microsoft.com/en-us/dotnet/standard/net-standard

**Comment by SeanFeldman** [comment]
Error on my end.
I'll release 2.0.1 to address that.
