### ISSUE TITLE
Version 2.x.x dependency should be .NET 4.61

### ISSUE THREAD

**Issue by darrenshrwd** [SeanFeldman/ServiceBus.AttachmentPlugin#23]
The new 2.0 nuget package requires .NET 4.6.2.  However 4.6.1 that is the lowest common support of .NET standard 2.0 (https://docs.microsoft.com/en-us/dotnet/standard/net-standard) and that would match with Microsoft.Azure.ServiceBus v2.0.0

**Comment by SeanFeldman** [comment]
Sorry for the inconvenience.
PR #22 is merged and [2.0.1 is released](https://www.nuget.org/packages/ServiceBus.AttachmentPlugin/2.0.1).
