### ISSUE TITLE
how to use topics instead queues ? 

### ISSUE THREAD

**Issue by kosnkow** [SeanFeldman/ServiceBus.AttachmentPlugin#247]
this is more like a question, in the implementation I saw that only supported is queue , topic not yet, true ?

**Comment by SeanFeldman** [comment]
The plugin is not designed to be used with queues or topics. It's designed to be used with message senders/receivers. The claim-check pattern is implemented on the `Message` type. And messages can be sent to either. Hope that answers the question.

Note: the project is on hold as there are changes coming to ASB service that will potentially obsolete the need in the plugin.
