### ISSUE TITLE
Transient error leads to container not found exception

### ISSUE THREAD

**Issue by rmt2021** [SeanFeldman/ServiceBus.AttachmentPlugin#258]
**Describe the bug**
We find that a transient error (e.g., temporary 503 server is busy) in `CreateIfNotExistsAsync`/`ExistsAsync` can lead to an unhandled container not found exception.
More concretely, in `BeforeMessageSend` 
```
try
{
  // Will only work for Shared Key or Account SAS. For Container SAS will throw an exception.
  if (! await container.ExistsAsync().ConfigureAwait(false))
  {
    await container.CreateIfNotExistsAsync().ConfigureAwait(false);
  }
}
catch (StorageException)
{
  // swallow in case a container SAS is used
}
...
await blob.UploadFromByteArrayAsync(message.Body, 0, message.Body.Length).ConfigureAwait(false);
```
If `CreateIfNotExistsAsync` or `ExistsAsync` fails due to some transient error (like when the server is busy), the exception will be swallowed in the catch block without being checked. As a result, the container is not successfully created. The following upload operation will fail due to the container not found exception.

**To Reproduce**
As shown above, when the `CreateIfNotExistsAsync` in `BeforeMessageSend` fails due to a transient error, container not found exception will happen in the following blob operations.

**Expected behavior**
The exception should be checked in the catch block to decide whether to swallow/retry/rethrow depending on the exception type. For example, if it is caused by some transient error, it can either retry or just rethrow the exception.

**Additional context**
We are willing to send a PR to help on this issue, if retry/rethrow the transient error exception is considered as a better practice than swallow.

**Comment by SeanFeldman** [comment]
@rmt2021 that's a valid point. If you'd like to submit a PR go ahead. I'll review and merge if all good. Thank you.

**Comment by rmt2021** [comment]
@SeanFeldman Thanks for your reply.
I think a good fix should be to check the error code in the exception to decide the reason of the exception and the further actions to take. If it is caused by "a container SAS is used", we can just swallow the exception as it is doing now; otherwise we can just throw the exception (or retry the operation).
I am trying to implement that but I am not sure which error code means "a container SAS is used" from the official doc https://docs.microsoft.com/en-us/rest/api/storageservices/blob-service-error-codes
Or do you have any idea on how to distinguish between exceptions caused by SAS issue or other problems?

**Comment by SeanFeldman** [comment]
[The list](https://docs.microsoft.com/en-us/rest/api/storageservices/blob-service-error-codes) you're referring to is talking about the server-side errors. Inability to create a SAS token is unlikely a server-side error but rather a client-side as it's the SDK attempting to use the provided credentials to generate the SAS token. And if credentials are anything other than account name/key, it's not possible.
