### ISSUE TITLE
Usage of plugin in triggered Azure functions

### ISSUE THREAD

**Issue by RickCSharp** [SeanFeldman/ServiceBus.AttachmentPlugin#31]
Hi Sean!

I have known about your plugin through our colleague Clemens.
We're trying to use the plugin via functions triggered by the presence of messages in the queue.
_Is it even possible?_

Input: We can write the message OK, and a blob is created.
Output: we read the message but the payload is empty...

This is the code of the function that reads the new message in the queue:

using System;
using System.Threading.Tasks;
public static void **Run**(string myQueueItem, TraceWriter log)
{
    log.Info($"C# ServiceBus queue trigger function processed message: {myQueueItem}"); \\ empty
}

These are the bindings 
 {
  "bindings": [
    {
      "name": "myQueueItem",
      "type": "serviceBusTrigger",
      "direction": "in",
      "queueName": "test_attachment",
      "connection": "Name_of_the_Company-sbus_RootManageSharedAccessKey_SERVICEBUS",
      "accessRights": "Manage"
    }
  ],
  "disabled": false
}

**Comment by SeanFeldman** [comment]
@RickCSharp I haven't tried this scenario. As any other plugin, it would need to be configured and registered with the ASB client, which tells me that the provided ASB binding would not be suitable and would need to be replaced by a custom one. In that case, the scenario above would work. Would you like to try it?

**Comment by SeanFeldman** [comment]
I've briefly looked into how `ServiceBusTrigger` is working. When a [`MessageReceiver` is created](https://github.com/Azure/azure-webjobs-sdk/blob/f70476485521b73f9023ba3b46d8baed5157173c/src/Microsoft.Azure.WebJobs.ServiceBus/MessagingProvider.cs#L37), it would need to be configured with the attachment plugin. Theoretically, it should be possible to create a custom trigger using this approach that would be based on the existing one.

**Comment by RickCSharp** [comment]
Hi Sean
I am happy to contribute to the project.
I will write to you to see if I am going in the right direction :-)
Take care
Riccardo

**Comment by SeanFeldman** [comment]
@RickCSharp have you tried anything so far?
I might have some time to play with this. If you don't want to post here, ping me via email (feldman.seat at gmail).

**Comment by SeanFeldman** [comment]
@RickCSharp I was a bit busy releasing support for KeyVault and MSI.
At the MVP summit earlier this month I spoke with @jeffhollan about enabling support for ASB plugins. If that comes, you should be able to use SB.AttachmentPlugin.

**Comment by SeanFeldman** [comment]
@RickCSharp if you still want the functionality, there's an [issue](https://github.com/Azure/azure-functions-host/issues/2504) with Azure Functions. Cast your vote there 🙂 
https://github.com/Azure/azure-functions-host/issues/2504

**Comment by thiagosoeiro** [comment]
Any updates on this?

**Comment by SeanFeldman** [comment]
@thiagosoeiro I'm not sure how re-posting this question here helps. The bottleneck is not the plugin, but Azure Functions (host?) since it doesn't allow _any_ plugins registration. Therefore the [question you posted](https://github.com/Azure/azure-functions-host/issues/2504#issuecomment-436372668) on the issue for Functions feature request is the one you want to persist asking.

**Comment by thiagosoeiro** [comment]
> @thiagosoeiro I'm not sure how re-posting this question here helps. The bottleneck is not the plugin, but Azure Functions (host?) since it doesn't allow _any_ plugins registration. Therefore the [question you posted](https://github.com/Azure/azure-functions-host/issues/2504#issuecomment-436372668) on the issue for Functions feature request is the one you want to persist asking.

Thanks!
