### ISSUE TITLE
Improve performance in BeforeMessageSend()

### ISSUE THREAD

**Issue by adnanrahat** [SeanFeldman/ServiceBus.AttachmentPlugin#37]
In AzureStorageAttachment::BeforeMessageSend(), the code looks like as            

            _await InitializeClient().ConfigureAwait(false);
            if (!configuration.MessageMaxSizeReachedCriteria(message))
            {
                return message;
            }_

I think bringing down the InitializeClient() after the MaxMessage check should improve the performance of the SendMessage call(). Other way to say, for smaller message, we won't initialize the blob clients anymore. Thoughts?

**Comment by SeanFeldman** [comment]
Done. Thank you @adnanrahat.
This is what's done in `AfterMessageReceive` and should have been done in `BeforeMessageSend` as well.
