### ISSUE TITLE
Attachment idempotency

### ISSUE THREAD

**Issue by SeanFeldman** [SeanFeldman/ServiceBus.AttachmentPlugin#40]
This was suggested during [ASB client's message size bug conversation](https://github.com/Azure/azure-service-bus-dotnet/issues/109#issuecomment-384817088).

When message is not sent successfully and retried, the plugin will create a duplicate blob.
This could be prevented by making the plugin idempotent. Since information about blob is stored in the message headers, this information can be used to determine if an attachment blob should be created or not.

Things to consider:
- A way to disable idempotency
  - What are the reasons to want to disable it?
- What happens if a new message is a clone of another message that happened to have `MessagePropertyToIdentifyAttachmentBlob` header?

**Comment by tomkerkhove** [comment]
This is a nice feature! Just curious - How will you track the idempotency? Via a flag that you already created the blob?

**Comment by SeanFeldman** [comment]
> information about blob is stored in the message headers

**Comment by SeanFeldman** [comment]
- "A way to disable idempotency" - won't implement until is requested.
- "What happens if a new message is a clone of another message that happened to have" - clones are created by developers, that will be in charge of removing the header from the clones if needed.
