### ISSUE TITLE
No need to multitarget 

### ISSUE THREAD

**Issue by SeanFeldman** [SeanFeldman/ServiceBus.AttachmentPlugin#42]
`<TargetFrameworks>netstandard2.0;net461</TargetFrameworks>`

[`net461` implements `netstandard2.0`](https://docs.microsoft.com/en-us/dotnet/standard/net-standard) therefore no need to multi-target.
Should be  `<TargetFramework>netstandard2.0</TargetFramework>`

**Comment by nemakam** [comment]
Looks like this is indeed causing a problem.
Will have to revert this change for next release. Multiple people have complained.
In VS2017, it works, but in VS2015 it doesn't as it doesn't know how to make sense of the net standard package (though it should ideally work on 4.6.1)

**Comment by nemakam** [comment]
Take a look at - https://github.com/dotnet/standard/issues/481
They have a few workarounds present which did not easily work out when I tried. But either way, I would think its better to revert this change

**Comment by SeanFeldman** [comment]
So "standard" is not what it means... sigh 🙁
I'll add `<TargetFrameworks>netstandard2.0;net461</TargetFrameworks>` back.

**Comment by SeanFeldman** [comment]
3.0.1 will address this.
