### ISSUE TITLE
Add a sample to the ASB samples repo

### ISSUE THREAD

**Issue by SeanFeldman** [SeanFeldman/ServiceBus.AttachmentPlugin#45]
Samples repo: https://github.com/Azure/azure-service-bus/tree/master/samples/DotNet

**Comment by djrosanova** [comment]
I will get this done!

**Comment by SeanFeldman** [comment]
@djrosanova there's a [test app](https://github.com/SeanFeldman/ServiceBus.AttachmentPlugin.KeyVaultProvider/tree/develop/src/KeyVaultProvider.TestApp) that could be used as a sample base if you'd like.

**Comment by SeanFeldman** [comment]
Cloud Design Patterns has added [Claim Check pattern documentation](https://docs.microsoft.com/en-us/azure/architecture/patterns/claim-check#claim-check-generation-with-service-bus) with ASB implementation using `ServiceBus.AttachmentPlugin`. It also include [code sample](https://github.com/mspnp/cloud-design-patterns/tree/master/claim-check/code-samples/sample-3).
