### ISSUE TITLE
SourceLink is not working with .NET Framework

### ISSUE THREAD

**Issue by SeanFeldman** [SeanFeldman/ServiceBus.AttachmentPlugin#48]
There is currently a bug with Visual Studio 2017 [SDK-style projects](https://github.com/dotnet/sdk/issues/1458) that prevents Source Link from working when the project targets the .NET Framework. A [workaround](https://github.com/dotnet/sdk/issues/1458#issuecomment-362685678) for the bug is to add the [SourceLink.Copy.PdbFiles NuGet package](https://www.nuget.org/packages/SourceLink.Copy.PdbFiles) to the project.

**Comment by ctaggart** [comment]
We sure you get SourceLink.Copy.PdbFiles 2.8.3 just published which has the updated workaround

**Comment by SeanFeldman** [comment]
Fixed by #54

**Comment by ctaggart** [comment]
Nice work @SeanFeldman
