### ISSUE TITLE
Microsoft.Azure.ServiceBus.ServiceBusCommunicationException

### ISSUE THREAD

**Issue by loga0060** [SeanFeldman/ServiceBus.AttachmentPlugin#50]
---
name: Microsoft.Azure.ServiceBus.ServiceBusCommunicationException

I have checked the connection string and it is fine. It does store a file in the blob but doesn't send message to ASB is there a setting i am missing 
---

**Describe the bug**

Microsoft.Azure.ServiceBus.ServiceBusCommunicationException
  HResult=0x80131500
  Message=No connection could be made because the target machine actively refused it ErrorCode: ConnectionRefused
  Source=Microsoft.Azure.ServiceBus
  StackTrace:
   at Microsoft.Azure.ServiceBus.Core.MessageSender.<OnSendAsync>d__44.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.ServiceBus.RetryPolicy.<RunOperation>d__18.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Azure.ServiceBus.RetryPolicy.<RunOperation>d__18.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.ServiceBus.Core.MessageSender.<SendAsync>d__31.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SbStoragePlugin.Program.<Main>d__3.MoveNext() in 
Inner Exception 1:
SocketException: No connection could be made because the target machine actively refused it
**To Reproduce**

Here is the code i am using -

``` c#
public static async Task Main(string[] args)
        {
            var storageConfiguration = new AzureStorageAttachmentConfiguration(StorageAccountConnectionString, "claimcheck");
            var queueClient = new QueueClient(ServiceBusConnectionString, QueueName);
            queueClient.RegisterAzureStorageAttachmentPlugin(storageConfiguration);

            Task OnMessageHandlerExceptions(ExceptionReceivedEventArgs exceptionArgs)
            {
                Console.WriteLine($"Exception recieved in the message handler: {exceptionArgs.Exception.Message}");
                return Task.CompletedTask;
            }

            var messageHandlerOptions = new MessageHandlerOptions(OnMessageHandlerExceptions)
            {
                AutoComplete = false
            };

            queueClient.RegisterMessageHandler(async (message, token) =>
            {
                Console.WriteLine($"Received message: {message.MessageId}");
                await queueClient.CompleteAsync(message.SystemProperties.LockToken);
            }, messageHandlerOptions);

            var random = new Random();
            for (var i = 0; i < 10; i++)
            {
                var messageBytes = new byte[10 * 1024];
                random.NextBytes(messageBytes);

                var message = new Message(messageBytes)
                {
                    MessageId = Guid.NewGuid().ToString()
                };

                await queueClient.SendAsync(message);
                Console.WriteLine($"Sent message: {message.MessageId}");
            }

            Console.ReadKey();
            await queueClient.CloseAsync();
        }
```

**Comment by SeanFeldman** [comment]
The exception (`Microsoft.Azure.ServiceBus.ServiceBusCommunicationException`) with message "No connection could be made because the target machine actively refused it ErrorCode: ConnectionRefused" indicates either an issue with ASB connection string or connectivity issues. Have you tried sending a message using ASB connection string w/o attachment plugin?

**Comment by loga0060** [comment]
Sean thanks for the reply, it looks like a firewall issue i just tried it from my home and it works.

**Comment by SeanFeldman** [comment]
👍 sounds good
