### ISSUE TITLE
Question: Compatibility with Service bus client 3.x

### ISSUE THREAD

**Issue by Blackbaud-DanHamlin** [SeanFeldman/ServiceBus.AttachmentPlugin#56]
Has any testing been done with newer version of Microsoft.Azure.ServiceBus.
It depends on >= 2.0.0 but 3.x is the current version.

**Comment by SeanFeldman** [comment]
The APIs of the ASB client required for the plugin to work have not changed since 2.0. Have you ran into a specific issue when using ASB 3.x client?

**Comment by SeanFeldman** [comment]
It works as expected. Please re-open issue if you find something that is not working. Thank you.
