### ISSUE TITLE
Make the ServiceBusAttachment.Plugin.dll strongly named

### ISSUE THREAD

**Issue by adnanrahat** [SeanFeldman/ServiceBus.AttachmentPlugin#78]
---
name: Feature request
about: Suggest an idea for this project

If a dll is not strongly named, it can't be used from other strongly named components. For that, it would be helpful to make the ServiceBusAttachment.Plugin strongly named. There are several benefits by making a dll strongly named as described here 
https://docs.microsoft.com/en-us/dotnet/framework/app-domains/strong-named-assemblies

---

**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. 
Example. I'm am trying to do [...] but [...]
I am trying to consume the library. However, other components of the library are strongly named, so it gives error.

**Describe the solution you'd like**
Here are the steps to sign an assembly with a strong name
https://docs.microsoft.com/en-us/dotnet/framework/app-domains/how-to-sign-an-assembly-with-a-strong-name

**Describe alternatives you've considered**
There are few alternatives:
1) Sign the dll and consume it from a static source
2) Consume the dll dynamically without signing.
3) Change the consumer to be unsigned (but that's hard as there are chain dependencies). 
**Additional context**

**Comment by SeanFeldman** [comment]
@adnanrahat sorry it took a while. 5.0.0 will be coming out shortly, along with this change.
