### ISSUE TITLE
Document optional cleanup

### ISSUE THREAD

**Issue by SeanFeldman** [SeanFeldman/ServiceBus.AttachmentPlugin#86]
The plugin looks at the `TimeToLive` property of the message sent out and sets a custom blob metadata `_ValidUntilUtc` if the value is other than `TimeSpan.MaxValue` if found.

In case it's deemed appropriate to remove the attachment blob, the receiving party could use blob ID represented by custom metadata [configured using plugin confusion API](https://github.com/SeanFeldman/ServiceBus.AttachmentPlugin#configure-message-property-to-identify-attachment-blob) in conjunction with the [container name](https://github.com/SeanFeldman/ServiceBus.AttachmentPlugin#configure-blob-container-name).

For receive only configured plugin, blob URI is provided via [blob URI custom metadata](https://github.com/SeanFeldman/ServiceBus.AttachmentPlugin#configure-message-property-for-sas-uri-to-attachment-blob).

**Comment by adnanrahat** [comment]
Couple options come in my mind 
1) Delete the blob at the end of AfterMessageReceive() has successfully retrieved the message from the blob. However, the risks of a failure happening in MessageReceiver code (which I think is called after the plugin method is invoked) need to considered. 
2) Set some policy to expire the message after some time. https://docs.microsoft.com/en-us/azure/storage/blobs/storage-lifecycle-management-concepts

**Comment by SeanFeldman** [comment]
Both options you've raise @adnanrahat don't really belong to the plugin itself and are heavily influenced by certain business rules. There are additional cases I can think of that cleanup strategy is difficult. For example, message that is an event. Which subscriber should perform the cleanup? How do individual subscribers know when the last subscriber has finished a successful processing of the message?

As for the Storage Lifecylce Management - again, that's a business decision that should not be mixed with the plugin implementation. As a builder of the system, you  are in a better position to define the policy. Not the plugin. You might be [deleting after certain period of time](https://docs.microsoft.com/en-us/azure/storage/blobs/storage-lifecycle-management-concepts#expire-data-based-on-age). Or [archive attachments](https://docs.microsoft.com/en-us/azure/storage/blobs/storage-lifecycle-management-concepts#move-aging-data-to-a-cooler-tier) to follow some sort of compliance. Or you might want to delete based on some categorization based on blob metadata (not supported yet).

Given all these edge cases, I lean towards leaving cleanup process out of the plugin and have it implemented according to the business rules of the users of the plugin. And that's the reason documenting what _can_ be done is welcomed, but implementing any cleanup will have way too many edge cases that will never do the job well for everyone.

**Comment by SeanFeldman** [comment]
[Cleanup section](https://github.com/SeanFeldman/ServiceBus.AttachmentPlugin/blob/develop/README.md#cleanup) added.
